"""
report.py - Generador de reportes QA en Markdown.
Proyecto: 001-portfolio-web
"""
from pathlib import Path
from datetime import datetime


def generate_report(project_name, project_path, static_issues, summary, llm_report):
    """Genera un reporte QA completo en Markdown."""
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    report_dir = Path(__file__).parent / "reports"
    report_dir.mkdir(exist_ok=True)
    report_path = report_dir / f"QA-{project_name}-{timestamp}.md"

    score = max(0, 100 - summary["errors"] * 5 - summary["warnings"] * 2 - summary["info"] * 0.5)

    if score >= 90:
        grade = "A"
        status = "✅ PASS"
    elif score >= 70:
        grade = "B"
        status = "⚠️ PASS WITH WARNINGS"
    elif score >= 50:
        grade = "C"
        status = "⚠️ NEEDS IMPROVEMENT"
    else:
        grade = "F"
        status = "❌ FAIL"

    lines = []
    lines.append(f"# QA Report - {project_name}")
    lines.append(f"")
    lines.append(f"**Fecha:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Proyecto:** {project_path}")
    lines.append(f"**Score:** {score:.0f}/100 ({grade})")
    lines.append(f"**Estado:** {status}")
    lines.append(f"")

    lines.append(f"## Executive Summary")
    lines.append(f"")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Issues | {summary['total']} |")
    lines.append(f"| Errors | {summary['errors']} |")
    lines.append(f"| Warnings | {summary['warnings']} |")
    lines.append(f"| Info | {summary['info']} |")
    lines.append(f"| Score | {score:.0f}/100 |")
    lines.append(f"| Grade | {grade} |")
    lines.append(f"")

    if summary["by_file"]:
        lines.append(f"## Issues by File")
        lines.append(f"")
        lines.append(f"| File | Errors | Warnings | Info |")
        lines.append(f"|------|--------|----------|------|")
        for fname, counts in sorted(summary["by_file"].items()):
            lines.append(f"| {fname} | {counts['errors']} | {counts['warnings']} | {counts['info']} |")
        lines.append(f"")

    errors = [i for i in static_issues if i["severity"] == "error"]
    warnings = [i for i in static_issues if i["severity"] == "warning"]
    info = [i for i in static_issues if i["severity"] == "info"]

    if errors:
        lines.append(f"## Errors ({len(errors)})")
        lines.append(f"")
        for issue in errors:
            file_ref = f"`{issue['file']}`" if issue.get("file") else ""
            lines.append(f"- {file_ref} {issue['message']}")
        lines.append(f"")

    if warnings:
        lines.append(f"## Warnings ({len(warnings)})")
        lines.append(f"")
        for issue in warnings:
            file_ref = f"`{issue['file']}`" if issue.get("file") else ""
            lines.append(f"- {file_ref} {issue['message']}")
        lines.append(f"")

    if info:
        lines.append(f"## Info ({len(info)})")
        lines.append(f"")
        for issue in info:
            file_ref = f"`{issue['file']}`" if issue.get("file") else ""
            lines.append(f"- {file_ref} {issue['message']}")
        lines.append(f"")

    lines.append(f"## LLM Analysis")
    lines.append(f"")
    lines.append(llm_report if llm_report else "_No LLM analysis available._")
    lines.append(f"")

    lines.append(f"## Recommendations")
    lines.append(f"")
    if summary["errors"] > 0:
        lines.append(f"1. **Fix all errors first** - These are critical issues that affect functionality or SEO")
    if summary["warnings"] > 0:
        lines.append(f"2. **Address warnings** - These improve quality and user experience")
    if summary["info"] > 0:
        lines.append(f"3. **Review info items** - Optional improvements for best practices")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"_Report generated by QA Agent - Project 001-portfolio-web_")

    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path
